name: "Setup Server Access"
description: "Sets up DigitalOcean, Container Registry, and Kubeconfig"
inputs:
  do_token:
    description: "DigitalOcean Access Token"
    required: true
  cluster_name:
    description: "Kubernetes Cluster Name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.do_token }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      shell: bash
      run: doctl registry login --expiry-seconds 1200

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      shell: bash
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 ${{ inputs.cluster_name }}

    - name: Set up Skaffold
      uses: yokawasa/action-setup-kube-tools@v0.9.2
      with:
        kubectl: "1.26.3"
        kustomize: "4.5.7"
        skaffold: "2.3.1"
