name: deploy-test-instance

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cached LFS checkout
        uses: nschloe/action-cached-lfs-checkout@v1.1.2
        with:
          exclude: "sentiment-ai/** docs/**"

      - name: Set unique namespace
        id: set_subdomain
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          UNIQUE_NAMESPACE="pr-${PR_NUMBER}"
          echo "UNIQUE_NAMESPACE=${UNIQUE_NAMESPACE}" >> $GITHUB_ENV
          echo "::set-output name=namespace::${UNIQUE_NAMESPACE}"

      - name: Setup Server Access
        uses: ./.github/setup-action
        with:
          do_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}

      - name: Configure App
        uses: ./.github/config-action
        with:
          container_registry: ${{ secrets.CONTAINER_REGISTRY }}
          ssl_secret: ${{ secrets.SSL_SECRET_NAME }}
          auth_secret: ${{ secrets.AUTH_SECRET_NAME }}
          jwt_option_token: ${{ secrets.JWT_OPTION_TOKEN_TEST}}
          cookie_option_key: ${{ secrets.COOKIE_OPTION_SECRET_KEY_TEST}}

      - name: Deploy to a unique testing environment with Skaffold
        run: skaffold run -p test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Post URL to pull request
        uses: JoseThen/comment-pr@v1.1.1
        with:
          comment: "Test environment has been updated."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
